export { default as IndexPage } from './IndexPage';
export { default as MapPage } from './MapPage';
export { default as SpeciesPage } from './SpeciesPage';
export { default as RecipesPage } from './RecipesPage';
export { default as InstructionsPage } from './InstructionsPage';
export { default as ImpressumPage } from './ImpressumPage';
export { default as PrivacyPolicyPage } from './PrivacyPolicyPage';
export { default as TermsUsePage } from './TermsUsePage';
export { default as IdentifyPage } from './IdentifyPage';
